version: "3.7"
services:
  battery-measurements-api:
    build: .
    ports:
      - "3006:3000"
    links:
      - db
    environment:
      - DATABASE_URL="mysql://db:3306/sonnen-db?user=sonnen&password=sonnen&useSSL=false"

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: sonnen-db
      MYSQL_USER: sonnen
      MYSQL_PASSWORD: sonnen
    volumes:
      - data-store:/var/lib/mysql

  test-db:
    image: mysql:5.7
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: sonnen-db
      MYSQL_USER: sonnen
      MYSQL_PASSWORD: sonnen

volumes:
  data-store:
