CREATE TABLE `accounts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `serial` int(11) DEFAULT NULL,
  `hw_version` decimal(5,2) DEFAULT NULL,
  `sw_version` varchar(255) DEFAULT NULL,
  `spree_version` int(11) NOT NULL DEFAULT '0',
  `brand` varchar(255) DEFAULT NULL,
  `product_name` varchar(255) DEFAULT NULL,
  `zip_code` varchar(255) DEFAULT NULL,
  `town` varchar(255) DEFAULT NULL,
  `street` varchar(255) DEFAULT NULL,
  `house_nr` varchar(255) DEFAULT NULL,
  `country_code` varchar(3) DEFAULT NULL,
  `latitude` float DEFAULT NULL,
  `longitude` float DEFAULT NULL,
  `timezone` varchar(255) DEFAULT NULL,
  `vpn_ip` varchar(255) DEFAULT NULL,
  `wan_ip` varchar(255) DEFAULT NULL,
  `mac_address` varchar(255) DEFAULT NULL,
  `token` varchar(255) DEFAULT NULL,
  `specified_capacity` decimal(8,2) DEFAULT NULL,
  `specified_pv_capacity` decimal(8,2) DEFAULT NULL,
  `inverter_power` decimal(8,2) DEFAULT NULL,
  `discharge` mediumint(9) DEFAULT NULL,
  `charge` mediumint(9) DEFAULT NULL,
  `production` mediumint(9) DEFAULT NULL,
  `consumption` mediumint(9) DEFAULT NULL,
  `state_of_charge` tinyint(4) DEFAULT NULL,
  `bhkw` tinyint(1) DEFAULT NULL,
  `bhkw_power` int(11) DEFAULT NULL,
  `vpp` varchar(255) DEFAULT NULL,
  `restrict_access` tinyint(1) DEFAULT '0',
  `average_request_time` decimal(4,2) NOT NULL DEFAULT '5.00',
  `online` tinyint(1) NOT NULL DEFAULT '1',
  `lumenaza_reduced_at` datetime DEFAULT NULL,
  `measured_at` datetime DEFAULT NULL,
  `last_alive_check_at` datetime DEFAULT NULL,
  `last_seen_at` datetime DEFAULT NULL,
  `fetched_at` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `index_accounts_on_serial` (`serial`),
  UNIQUE KEY `index_accounts_on_token` (`token`),
  UNIQUE KEY `index_accounts_on_mac_address` (`mac_address`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;