CREATE TABLE `cellpack_data` (
  `serial` mediumint(8) unsigned NOT NULL,
  `timestamp` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
  `module_id` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `system_time` int(10) unsigned DEFAULT NULL,
  `system_status` int(10) unsigned DEFAULT NULL,
  `system_alarm` int(10) unsigned DEFAULT NULL,
  `system_warning` int(10) unsigned DEFAULT NULL,
  `charge_current_limit` mediumint(8) unsigned DEFAULT NULL,
  `discharge_current_limit` mediumint(8) unsigned DEFAULT NULL,
  `system_current` mediumint(9) DEFAULT NULL,
  `system_avg_current` mediumint(9) DEFAULT NULL,
  `max_module_current` mediumint(9) DEFAULT NULL,
  `min_module_current` mediumint(9) DEFAULT NULL,
  `system_dc_voltage` mediumint(8) unsigned DEFAULT NULL,
  `max_module_dc_voltage` mediumint(8) unsigned DEFAULT NULL,
  `min_module_dc_voltage` mediumint(8) unsigned DEFAULT NULL,
  `max_cell_voltage` smallint(5) unsigned DEFAULT NULL,
  `min_cell_voltage` smallint(5) unsigned DEFAULT NULL,
  `max_cell_temp` smallint(5) unsigned DEFAULT NULL,
  `min_cell_temp` smallint(5) unsigned DEFAULT NULL,
  `rsoc` smallint(5) unsigned DEFAULT NULL,
  `remaining_capacity` mediumint(8) unsigned DEFAULT NULL,
  `full_charge_capacity` mediumint(8) unsigned DEFAULT NULL,
  `soh` smallint(5) unsigned DEFAULT NULL,
  `cycle_count` smallint(5) unsigned DEFAULT NULL,
  PRIMARY KEY (`serial`,`timestamp`,`module_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;